✨ feature(actions): adjust how template cloning works and bump gradle
nea89o/Forge1.8.9Template pull request #31
Opened 2024-04-28 03:44 UTC by pauliesnug

some of this is definitely opionated. if needed I can remove the editorconfig and gradle aliases etc.
i also need to steup ID replacement, but I'm not sure if that should just be `%NAME%` lowercase, or something else with blossom maybe?

2024-04-28 16:26 UTC, nea89o requested changes

2024-04-28 16:26 UTC, nea89o commented on .editorconfig
> +ij_java_imports_layout = $*,|,java.**,|,javax.**,|,*,|,net.minecraft.**,|,org.polyfrost.**
I don't think this project has any polyfrost dependencies, so i don't think we need to separate them here.

2024-04-28 16:26 UTC, nea89o commented on .editorconfig
> +indent_style = tab
I would rather not use tabs for anything. They change depending on the editor and are generally not as nice if you want smaller indents inside of function calls for example.

2024-04-28 16:26 UTC, nea89o commented on .github/workflows/template-cleanup.yml
> +            LICENSE
Could you move this back into a script file so you can still call the script without using github actions?

2024-04-28 16:26 UTC, nea89o commented on build.gradle.kts
> -val modid: String by project
I think those should stay as normal `val`s here, since we use them in multiple places. Especially `properties("modID").get()` everywhere is probably worse than declaring all of the properties here once.

2024-04-28 16:26 UTC, nea89o commented on .github/workflows/template-cleanup.yml
> +          find src -type f -exec sed -i "s/org.jetbrains.plugins.template/$GROUP/g" {} +
Is there a reason you refer to `org.jetbrains.plugins.template` here instead of `com.example`? That is not the package we use. Would changing this package allow better compatibility with something else or is this unintentional?

2024-04-28 16:27 UTC, nea89o commented
> blossom maybe

We can use blossom for injecting the version into the `@Mod` annotation, but i dont think we need it for the general template initialization. Maybe in another PR.

2024-04-28 21:44 UTC, pauliesnug commented on .editorconfig
> +ij_java_imports_layout = $*,|,java.**,|,javax.**,|,*,|,net.minecraft.**,|,org.polyfrost.**
> I don't think this project has any polyfrost dependencies, so i don't think we need to separate them here.

oops! forgor to remove that

2024-04-28 21:44 UTC, pauliesnug commented on .editorconfig
> +indent_style = tab
thats fair

2024-04-28 21:45 UTC, pauliesnug commented on .github/workflows/template-cleanup.yml
> +            LICENSE
sure!

2024-04-28 21:45 UTC, pauliesnug commented on build.gradle.kts
> -val modid: String by project
imo it makes it more clear than just declaring a bunch of by projects. but i guess we  can keep them

2024-04-28 21:45 UTC, pauliesnug commented on .github/workflows/template-cleanup.yml
> +          find src -type f -exec sed -i "s/org.jetbrains.plugins.template/$GROUP/g" {} +
this was unintentional, i copied code across from another project

2024-04-28 21:46 UTC, pauliesnug commented on .editorconfig
> +indent_style = tab
> I would rather not use tabs for anything. They change depending on the editor and are generally not as nice if you want smaller indents inside of function calls for example.

tabs are generally better for accessibility and i prefer them on certain file types, but its your template so i can change it :3

2024-04-29 08:36 UTC, nea89o commented on .editorconfig
> +indent_style = tab
> tabs are generally better for accessibility
Maybe in principle, but in practice there are still so many editors that just handle tabs terribly. Some people who prefer tabs might like using accessibility as an argument, but if you are having problems with your eyesight (like me, for example), you are better off configuring your editor in ways that also handle files with a spaced indent, or having your editor add other visual aids such as lines for indents or different colored indents per block. Tabs are not more accessible out of the box and the arguably little accessibility you get is quickly overshadowed by even small plugins. I personally still prefer tabs because they let me customize the indent width very easily, but i think using the almighty cudgel of accessibility here is not really right and for a template like this i want consistency that tabs cannot offer.

2024-04-29 08:38 UTC, nea89o commented on build.gradle.kts
> -val modid: String by project
You could also use `val mcVersion : String by project.properties` if you think that is more clear.

2024-07-29 08:12 UTC, closed without merging